script:
- stack +RTS -N2 -RTS --no-terminal --skip-ghc-check --stack-yaml $STACKYAML test
matrix:
  include:
  - env: GHCVER=7.8.4 STACKYAML=stack-7.8.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
        - libgmp-dev
  - env: GHCVER=7.10.1 STACKYAML=stack-7.10.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.1
        - libgmp-dev
install:
- stack +RTS -N2 -RTS --no-terminal --skip-ghc-check --stack-yaml $STACKYAML setup
- stack +RTS -N2 -RTS --no-terminal --skip-ghc-check --stack-yaml $STACKYAML test
  --only-snapshot
cache:
  directories:
  - ~/.stack
  apt: true
before_install:
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
- export PATH=~/.local/bin:$PATH
- if [ ! -e ~/.local/bin/stack ]; then mkdir -p ~/.local/bin; travis_retry curl -L
  https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz
  | gunzip > ~/.local/bin/stack; chmod a+x ~/.local/bin/stack; fi
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
  '?')]"
- stack +RTS -N2 -RTS --version
language: c
sudo: false
